version: '3.9'
services:

  database:
    container_name: recipe_database
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: TiseTheCat
      POSTGRES_PASSWORD: FoodLover
      POSTGRES_DB: RECIPE_DEV