version: '3.9'
services:

  postgres:
    image: postgres:alpine
    restart: always
    container_name: recipe_database
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: TiseTheCat
      POSTGRES_PASSWORD: FoodLover